{{- if not .Values.slack.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "boothby.fullname" . }}-slack
  labels:
    {{- include "boothby.labels" . | nindent 4 }}
type: Opaque
data:
  SLACK_CLIENT_ID: Zm9v
  SLACK_CLIENT_SECRET: Zm9v
  SLACK_SIGNING_SECRET: YmFy
{{- end }}
