apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "souvenirs.fullname" . }}-web
  labels:
    {{- include "souvenirs.labels" . | nindent 4 }}
    component: web
data:
  config.json: '{{ .Values.web.config }}'
