apiVersion: v1
kind: Service
metadata:
  name: {{ include "souvenirs.fullname" . }}-api
  labels:
    {{- include "souvenirs.labels" . | nindent 4 }}
    component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: api
      protocol: TCP
      name: http
  selector:
    {{- include "souvenirs.selectorLabels" . | nindent 4 }}
    component: api
